name: CI

env:
  DOCKER_REGISTRY_URL: luckyj5.jfrog.io/spring-petclinic-docker
  DOCKER_IMAGE: spring-petclinic
  TAG: latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package

    - name: Run tests
      run: mvn -B test

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_REGISTRY_URL/$DOCKER_IMAGE:$TAG .
        echo "${{secrets.JFROG_ACCESS_TOKEN}}" | docker login $DOCKER_REGISTRY_URL -u ${{ secrets.JF_USER }} --password-stdin

    - name: Push Docker Image to Docker Hub
      run: docker push $DOCKER_REGISTRY_URL/$DOCKER_IMAGE:$TAG

    - name: Cleanup
      run: |
        docker logout $DOCKER_REGISTRY_URL
