name: CI

env:
  DOCKER_REGISTRY_URL: luckyj5.jfrog.io/artifactory/spring-petclinic-docker
  TAG: latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package

    - name: Run tests
      run: mvn -B test

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_REGISTRY_URL:$TAG .
        docker login $DOCKER_REGISTRY_URL -u ${{ secrets.JF_ACCESS_TOKEN }} -p ${{ secrets.JF_ACCESS_TOKEN }}
        docker push $DOCKER_REGISTRY_URL:$TAG

    - name: Cleanup
      run: |
        docker logout $DOCKER_REGISTRY_URL
